### ISSUE TITLE
Docker container for testing

### ISSUE THREAD

**Issue by bdshroyer** [rabbitmq/rabbitmq-cli#1]
AS A RabbitMQ developer
I WANT the CLI tests to run in a Docker container
SO THAT I don't have to install Elixir when I'm not working on the CLI

NOTE: This may be very slow relative to the actual tests. We may ultimately want a flag in there to let you run tests locally if you have Elixir installed.

**Comment by michaelklishin** [comment]
Closing since our team agreed that primarily using the umbrella repo is optimal for this subproject: it usually involves building the node from source with a certain set of plugins and messing with its state, so it's not clear whether a Docker image can contribute something beyond running all that in a container.

If specific examples of where this would be useful arise we'd reconsider this.
