### ISSUE TITLE
Introduce a command or option  to set_policy for all vhosts in a RabbitMQ cluster

### ISSUE THREAD

**Issue by ichandan16** [rabbitmq/rabbitmq-cli#281]
As an admin, we should have a command or option to set policy for all vhosts in a RabbitMQ cluster.
Right now we are using `-p` switch for a specific vhost or without it applies only on `/` vhost. 

For an example, if I have a queue named myqueuedev in my Dev environment and I want to have to implement mirrored queue, I am relying on:

```rabbitmqctl set_policy -p $vhost mq-ha "^myqueue*" '{"ha-mode":"exactly","ha-params":2,"ha-sync-mode":"automatic"}'```

Now if I have a queue named myqueueqa in QA environment and the original queue is in different vhost, I have to set another policy targeting the corresponding vhost.

It would be nice to have a command option to set the same policy on all the vhosts with same regex name.

**Comment by michaelklishin** [comment]
I have my doubts about such features. They are dangerous. You can use [definitions import](http://www.rabbitmq.com/management.html#load-definitions) to preconfigure clusters already.

**Comment by lukebakken** [comment]
This is easy enough to script via the command line that I agree with @michaelklishin

**Comment by ichandan16** [comment]
We have a script that does the task. 
```# vhosts=$(rabbitmqctl list_vhosts | grep -v vhost); for vhost in $vhosts; do echo "Host: $vhost-----------"; rabbitmqctl set_policy -p $vhost myqueue-ha "^myqueue*" '{"ha-mode":"exactly","ha-params":2,"ha-sync-mode":"automatic"}'; done```

We were looking for an elegant way to do this. Appreciate it, if you can help us understanding the negetive impact of it.

Thanks,
Chandan

**Comment by michaelklishin** [comment]
Our team does not use issues for discussions but this one is specific enough so here it goes.

We have a number of commands like this (affecting all vhosts or queues or similar) suggested, e.g. #145 and #146. Such commands would often not accept a virtual host parameter. Which means it is extremely easy to use one of those by accident and delete or override something for every virtual host instead of just the default one (which may or may not even exist).

Even if we introduce confirmations there would be a way to pass a `-y` (if we use `apt` as example) for scripting, so only interactive use gets easier.

On the contrary it is quite hard to misuse definitions import, for example: you have to produce an incorrect document instead of invoking the wrong command.

**Comment by michaelklishin** [comment]
I don't see anything particularly unelegant about a script that iterates over virtual hosts. You probably want to add `-q` or, starting with 3.7.10, `-s` to only get the virtual host rows. The script is short, to the point and easy to understand.

**Comment by michaelklishin** [comment]
I am increasingly convinced that such commands would be harmful and [definition import](https://www.rabbitmq.com/definitions.html), HTTP API or CLI tool scripting are reasonable alternatives.
