### ISSUE TITLE
rabbitmq-diagnostics cipher_suites command doesn't show all available ciphers

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-cli#342]
#141 and #147 introduced the `rabbitmq-diagnostics cipher_suites` command which is useful but only shows all of the enabled ciphers for the Erlang VM, not all _available_ ciphers. This can give users the mistaken impression that certain ciphers aren't available, as in [this `rabbitmq-users` discussion](https://groups.google.com/d/topic/rabbitmq-users/LhNzYErhqO4/discussion).

We can add an `--all` argument or default the output to all available ciphers instead of all enabled, or come up with something that explains this better to reduce confusion. For instance, we could require a user to provide either `--all` or `--enabled` so they know what is going on.

As a workaround, the following command lists all available ciphers:

```
rabbitmqctl eval 'ssl:cipher_suites(all).'
```

**Comment by michaelklishin** [comment]
We cannot require an argument. There has to be a default. We can list all by default and add a switch for listing enabled only (--enabled like `rabbitmq-plugins list` uses)

**Comment by lukebakken** [comment]
> We cannot require an argument

Is that a limitation of how the cli library works? I actually think requiring the user to provide an argument isn't such a bad idea - it's educational. The help output that would be shown would then explain why they need to choose between "default" (i.e. enabled) and "all" (available) ciphers (the two terms used in the [`cipher_suites`](http://erlang.org/doc/man/ssl.html#cipher_suites-2) function).

Also, it appears that only `cipher_suites/2` is supported and the other versions will be deprecated.

**Comment by michaelklishin** [comment]
No, these are general expectations of a user, at least given how our docs have been and how other commands work. `rabbitmq-plugins list` does not require `--enabled | --disabled | --all` to be explicitly provided, for example.

The docs basically suggest that all available suites will be printed. Let's make it so.

**Comment by hairyhum** [comment]
`rabbitmq-plugins list` uses a specific formatter, which shows which plugins are enabled and actually supports the `--enabled` flag to list enabled plugins only, while `cipher_suites` lists suites in a copy-paste friendly format.
We may implement an extended format, which will show if a suite is enabled or not, similar to the plugins list command. BTW, erlang ssl API does not call them enabled, but default because you can still use disabled ones.
For the copy-paste friendly format we may stay closer to the ssl API and use `--default | --all`. Because having `--default` flag disabled by default is confusing.
We can also make it closer to the `ssl:cipher_suites` API by supporting `--anonymous` flag and `--tls-version` flag, but that may be out of scope.

**Comment by michaelklishin** [comment]
Supporting alternative formatters sounds good. I think `--tls-version` is out of scope. Ideally the default should be what can be copied to the config file.

**Comment by michaelklishin** [comment]
`3.7.15` and later versions will support `--format=(openssl | erlang | map)` and `--all`.
